server:
    port: 8080

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://0.0.0.0:5432/perimeter
        username: postgres
        password: P@ssw0rd
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    mvc:
        favicon:
            enabled: false
        static-path-pattern: /**
    resources:
        add-mappings: true
        static-locations: classpath:static
    jpa:
      hibernate:
        use-new-id-generator-mappings: true
        ddl-auto: create

flyway:
    enabled: false
    url: jdbc:postgresql://0.0.0.0:5432/perimeter
    user: postgres
    password: P@ssw0rd
    locations: classpath:db/migrations

security:
    basic:
        enabled: false

perimeter:
    teamIpPattern: 10.0.%d.1
    flag:
        ttl: 300
        pattern: ^[a-f0-9]{32}=$

themis:
    host: 127.0.0.1
    port: 5000
    protocol: http