spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://postgres:5432/perimeter
        username: postgres
        password: P@ssw0rd

perimeter:
    team:
        base-network: 10.255.0.0
        subnet-cidr: 24
        vulnbox-address: 2
        internal-ip: 10.255.0.5
        stats-port: 1936
        production-backend: prod
    flag:
        ttl: 300
        pattern: ^(?<flag>[a-fA-F0-9]{32}=)$
        jwt:
            enabled: true
            algorithm: EC256
            pattern: ^VolgaCTF\{(?<flag>.*)\}$
    exploit:
        execution-interval: 60000
    themis:
        host: 10.255.255.2
        port: 5000
        protocol: http
        integration-enabled: true
    agent:
        timeout: 20000
        delete-after: 100000
    git:
        root: git
