spring:
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

perimeter:
    server:
        host: 127.0.0.1
        port: 8080
        protocol: http
    configurator:
        templates-path: config_templates
        configurators:
            haproxy:
                config-path: /tmp/haproxy.cfg
                template-file: haproxy.cfg.j2
                apply-command: docker restart haproxy
                overrides:
                    host: 0.0.0.0